### ISSUE TITLE
can't open zip after download

### ISSUE THREAD

**Issue by Alexmg86** [jdwil/zip-stream#1]
hi! thanks for your package.
i have a some problem. i can't open zip after download.
working on laravel and my mac wrote, that zip is broken :(

**Comment by jdwil** [comment]
Hi @Alexmg86. Can you post some code / steps to help replicate the issue?

**Comment by Alexmg86** [comment]
yes, thanks
`public function downloadFiles($request)
    {
        $files = Attachment::where('archive', $request->archive)->get();
        $acthiveName = $this->makeZip($files, $request->archive);
        $name = 'file.zip';
        $headers = [
            'Content-Type' => 'application/octet-stream',
            'Content-Disposition' => 'attachment; filename="foo.zip"',
            'Content-Transfer-Encoding' => 'binary',
        ];
        return response()->download($acthiveName, $name, $headers)->deleteFileAfterSend(true);
    }

    public function makeZip($files, $archive)
    {
        $acthiveName = storage_path('app/archive/'.$archive.'.zip');
        $zip = ZipStream::forFile($acthiveName);
        foreach ($files as $file) {
            $arExt = [$file->extension, 'docx'];
            foreach ($arExt as $ext) {
                $fileNameOld = $file->archive.'/'.$file->name . '.' . $ext;
                $fileNameNew = $file->native . '.' . $ext;
                $exist = Storage::exists('uploaded/'.$fileNameOld);
                if($exist) {
                    $zip->addFileFromDisk($fileNameNew, storage_path('app/uploaded/'.$fileNameOld));
                }
            }
        }
        $zip->endFile();
        $zip->close();
        return $acthiveName;
    }`

**Comment by Alexmg86** [comment]
@jdwil i was find mistake. 
I was try "Dealing with huge data sets" and forget delete for "Basic Usage" this line:
$zip->endFile();
Thanks it's the best and faster package for zip

**Comment by jdwil** [comment]
@Alexmg86 Ah great. I'm glad you figured it out. Thanks for the compliment!
